# Generated by Django 3.1.7 on 2021-02-25 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20210225_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='partition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishs', to='backoffice.partitionformulla', verbose_name='Formule de partition'),
        ),
    ]
