# Generated by Django 3.1.7 on 2021-02-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_auto_20210225_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying',
            name='total_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name="Montant total de l'achat"),
            preserve_default=False,
        ),
    ]
