# Generated by Django 3.1.7 on 2021-02-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_auto_20210225_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='portion',
            name='stock_store',
            field=models.IntegerField(default=0),
        ),
    ]
