# Generated by Django 3.1.7 on 2021-02-26 15:54

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('backoffice', '0009_auto_20210226_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la boisson')),
            ],
            options={
                'verbose_name': 'Boisson',
                'verbose_name_plural': 'Boissons',
            },
        ),
        migrations.RemoveField(
            model_name='price',
            name='dish',
        ),
        migrations.AddField(
            model_name='price',
            name='content_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
