# Generated by Django 3.1.7 on 2021-02-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('backoffice', '0010_auto_20210226_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceentry',
            name='plat',
        ),
        migrations.AddField(
            model_name='invoiceentry',
            name='content_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='invoiceentry',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
