# Generated by Django 3.1.7 on 2021-02-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0011_auto_20210226_1626'),
        ('backoffice', '0011_auto_20210226_1612'),
    ]

    operations = [
    ]
