# Generated by Django 3.1.7 on 2021-03-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0012_merge_20210226_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('P', 'Portionable'), ('UP', 'Non Portionable')], default='P', max_length=2, verbose_name='Categorie du produit'),
        ),
    ]
