# Generated by Django 3.1.7 on 2021-03-01 16:48

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0013_auto_20210301_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portion',
            name='partition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.partitionformulla'),
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('portion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.portion')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
