# Generated by Django 3.1.7 on 2021-03-02 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0014_auto_20210301_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='partition',
        ),
        migrations.AddField(
            model_name='product',
            name='partition',
            field=models.ForeignKey(blank=True, help_text='Appuyez sur Shift pour selectionner plusieurs', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.partitionformulla', verbose_name="Type de préparation qu'on peut faire avec ce produit"),
        ),
    ]
