# Generated by Django 3.1.7 on 2021-02-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0014_invoice_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='table_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numéro de la table'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant'),
        ),
    ]
