# Generated by Django 3.1.7 on 2021-03-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0015_auto_20210227_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='content_id',
            new_name='object_id',
        ),
    ]
