# Generated by Django 3.1.7 on 2021-03-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0015_auto_20210302_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='partition',
        ),
        migrations.AddField(
            model_name='product',
            name='partition',
            field=models.ManyToManyField(blank=True, help_text='Appuyez sur Shift pour selectionner plusieurs', null=True, to='backoffice.PartitionFormulla', verbose_name="Type de préparation qu'on peut faire avec ce produit"),
        ),
    ]
