# Generated by Django 3.1.7 on 2021-03-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0016_auto_20210302_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='partition',
            field=models.ManyToManyField(blank=True, help_text='Appuyez sur Shift pour selectionner plusieurs', to='backoffice.PartitionFormulla', verbose_name="Type de préparation qu'on peut faire avec ce produit"),
        ),
    ]
