# Generated by Django 3.1.7 on 2021-03-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0017_auto_20210302_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfert',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
