# Generated by Django 3.1.7 on 2021-03-14 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0022_auto_20210305_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyingentry',
            name='partition',
        ),
        migrations.RemoveField(
            model_name='portion',
            name='partition',
        ),
        migrations.AddField(
            model_name='portion',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='portion', to='backoffice.product'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='partition',
        ),
        migrations.AddField(
            model_name='product',
            name='partition',
            field=models.OneToOneField(help_text='Appuyez sur Shift pour selectionner plusieurs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='backoffice.partitionformulla', verbose_name="Type de préparation qu'on peut faire avec ce produit"),
        ),
    ]
