# Generated by Django 3.1.7 on 2021-03-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0023_auto_20210314_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceentry',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyingentry',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantité achetée ou obtenue après portionnage'),
        ),
        migrations.AlterField(
            model_name='invoiceentry',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='backoffice.invoice'),
        ),
    ]
