# Generated by Django 3.1.7 on 2021-03-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0024_auto_20210316_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Montant'),
        ),
    ]
