# Generated by Django 3.1.7 on 2021-03-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0026_auto_20210316_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitionformulla',
            name='input_unit',
            field=models.CharField(default='', max_length=100, verbose_name="L'unité de mesure en entrée"),
        ),
        migrations.AlterField(
            model_name='partitionformulla',
            name='output',
            field=models.IntegerField(verbose_name='Nombre de portions'),
        ),
        migrations.AlterField(
            model_name='partitionformulla',
            name='portions_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nom de portion'),
        ),
    ]
